name: kekokuki
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  #main
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  logger: ^2.4.0
  dio: ^5.7.0
  hive: ^2.2.3
  get: ^4.7.2
  json_annotation: ^4.9.0
  client_information: ^2.1.4
  # network_type_detector: ^1.0.1
  retrofit: ^4.4.1
  flutter_timezone: ^1.0.8
  sqflite: ^2.3.3+1
  crypto: ^3.0.3
  webview_flutter: ^4.8.0
  flutter_native_splash: ^2.4.0
  flutter_easyloading: ^3.0.5
  easy_refresh: ^3.4.0
  # nim_core: 1.8.0
  floor: ^1.4.2
  sprintf: ^7.0.0
  flutter_swipe_action_cell: ^3.1.5
  # web_socket_channel: ^2.4.5
  # encrypt: ^5.0.3
  # video_player: ^2.9.2
  # photo_view: ^0.15.0
  open_settings: ^2.0.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  # wakelock: ^0.6.2
  # just_audio: ^0.9.41
  # audio_session: ^0.1.21
  # gif_view: ^0.3.1
  # svgaplayer_flutter: ^2.2.0
  lottie: ^3.0.0
  cached_network_image: ^3.3.1
  carousel_slider_plus: ^7.0.1
  # flutter_rating_bar: ^4.0.1
  # zego_express_engine: ^3.17.1
  auto_size_text: ^3.0.0

  # purachase
  # in_app_purchase: 3.1.7
  # in_app_purchase_storekit: 0.3.6+4
  # in_app_purchase_android: 0.3.0+7

  url_launcher: ^6.3.1
  # video_thumbnail: ^0.5.3
  flutter_datetime_picker_plus: ^2.2.0
  # smooth_page_indicator: ^1.2.0+3
  # flutter_fortune_wheel: ^1.3.2

  # #sign in
  # sign_in_with_apple: ^6.1.3
  # google_sign_in: ^6.2.1

  # rtm & rtc
  # agora_rtm: ^2.2.2
  agora_rtm: 1.5.9
  agora_rtc_engine: ^6.5.2

  # paging
  infinite_scroll_pagination: ^5.0.0
  audio_session: ^0.1.25
  just_audio: ^0.9.46
  video_player: ^2.9.5
  wakelock: ^0.6.2
  
  # data statistics
  # advertising_id: ^2.7.1
  # app_tracking_transparency: ^2.0.6
  # android_play_install_referrer: ^0.4.0
  # appsflyer_sdk: ^6.15.1
  # firebase_analytics: ^11.2.1
  # datatower_ai_core_flutter: 2.1.0
  # facebook_app_events: ^0.19.4

# dependency_overrides:
#  win32: 5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.8
  floor_generator: ^1.4.2
  pigeon: ^15.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
  field_prefix:

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animates/
    - assets/audios/
    - assets/fonts/
    - assets/images/tabs/
    - assets/images/common/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cascadia Code
      fonts:
        - asset: assets/fonts/kekokuki_cascadia_code.ttf
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
